project:
  type: website

website:
  title: "DANTE: NCAA Ratings"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: vrgl_ratings.qmd
        text: "MBB Ratings"
      - href: btrc_ratings.qmd
        text: "WBB Ratings"
      - href: about.qmd
        text: "About"
      - href: the_playlist.qmd
        text: "The Playlist"
    
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/matconner/
      - icon: github
        href: https://github.com/foxandfortune
      - icon: boombox-fill
        href: https://open.spotify.com/user/huntingthesnark
      - icon: book
        href: https://www.goodreads.com/author/show/20422355.Brandon_Conner
      - icon: youtube
        href: https://www.youtube.com/@Bless_Dem_Boyz


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

