project:
  type: website

website:
  title: "DANTE: NCAA Ratings"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - vrgl_ratings.qmd
      - btrc_ratings.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

